version: '3'

services:
  redis:
    image: redis
    command: redis-server --requirepass mysecurepasswordhere
    ports:
      - "6379:6379"

  
  mysqlsrv:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "MySql2019!"
      MYSQL_USER: dbuser
      MYSQL_DATABASE: "testedb"
    ports:
      - "3306:3306"
    networks:
      - mysql-compose-network

  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - mysql-compose-network

networks: 
  mysql-compose-network:
    driver: bridge